### ISSUE TITLE
Another failure with dev purrr

### ISSUE THREAD

**Issue by hadley** [LudvigOlsen/rearrr#2]
We've changed the iteration error (https://purrr.tidyverse.org/dev/reference/purrr_error_indexed.html) so now your tests are failing again:

```
Failure (test_dim_values.R:513): dim_values()
xpectr::strip(side_effects_19400[["error_class"]]) not equal to xpectr::strip(c(purrr_error, "error", "condition")).
Lengths differ: 4 is not 3
```

Do you mind either regenerating the tests or giving me the go ahead to submit to CRAN even though it breaks your package? Unfortunately I really need to get this patch release out we accidentally broke purrr on 32-bit windows.

**Comment by LudvigOlsen** [comment]
Hi @hadley 

Assuming this will only fail when testing the errors and doesn't affect the actual functions, you can go ahead. I'll fix it when it's uploaded.

Best,
Ludvig

**Comment by hadley** [comment]
Yup, thanks!

**Comment by LudvigOlsen** [comment]
Fixed and submitted
